  producer:
    build: ./producer
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    command: ["/wait-for-kafka.sh", "kafka:9092", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  consumer:
    build: ./consumer
    depends_on:
      - kafka
    command: ["/wait-for-kafka.sh", "kafka:9092", "python", "consumer.py"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PGHOST=ep-curly-recipe-a50hnh5z-pooler.us-east-2.aws.neon.tech
      - PGDATABASE=crimes
      - PGUSER=crimes_owner
      - PGPASSWORD=npg_QUkH7TfKZlF8
